apiVersion: apps/v1
kind: Deployment
metadata:
  name: udp-reader-deployment
  labels:
    app: udp-reader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udp-reader
  template:
    metadata:
      labels:
        app: udp-reader
    spec:
      hostNetwork: true # <-- CRITICAL: Bypasses K8s network and binds directly to the node's network
      dnsPolicy: ClusterFirstWithHostNet # Ensures internal K8s DNS still works for this pod
      containers:
      - name: udp-container
        image: kregistry.siwko.org:5000/udp-reader:latest
        # Note: You don't need ports or services defined anymore. 
        # The container has direct access to the Node's port 23229.